function renderGoals(){
  $('#goalCountLabel').textContent=state.goals.length+(state.goals.length===1?' goal':' goals');const grid=$('#goalsGrid');
  if(!state.goals.length){grid.innerHTML=emptyState('Create your first goal','Set a target amount and track contributions over time.');return;}
  grid.innerHTML=state.goals.map(g=>{const p=progressOfGoal(g),rem=Math.max(0,n(g.target)-n(g.current)),date=g.targetDate?parseLocalDate(g.targetDate):null,days=date?Math.ceil((date-startOfDay(new Date()))/86400000):null;return `<article class="finance-card"><div class="finance-card-header"><div><h3>${escapeHtml(g.name)}</h3><div class="subtitle">${g.targetDate?'Target '+formatDate(g.targetDate):'No target date'}</div></div><div class="card-menu"><button data-action="edit-goal" data-id="${g.id}">Edit</button><button class="delete" data-action="delete-goal" data-id="${g.id}">Delete</button></div></div><div class="balance-line"><strong>${money(g.current)}</strong><small>of ${money(g.target)}</small></div><div class="progress-track"><i style="width:${p}%"></i></div><div class="card-facts"><div class="fact"><span>Progress</span><strong>${percent(p)}</strong></div><div class="fact"><span>Remaining</span><strong>${money(rem,true)}</strong></div><div class="fact"><span>Time left</span><strong>${days===null?'—':days<0?'Past date':days+' days'}</strong></div></div><div class="card-actions"><button class="button primary" data-action="contribute-goal" data-id="${g.id}">Add contribution</button></div></article>`;}).join('');
}
function saveGoal(event){event.preventDefault();const id=$('#goalId').value;const goal={id:id||uid('goal'),name:$('#goalName').value.trim(),target:n($('#goalTarget').value),current:n($('#goalCurrent').value),targetDate:$('#goalDate').value||'',createdAt:id?(state.goals.find(g=>g.id===id)?.createdAt||Date.now()):Date.now()};if(!goal.name||goal.target<=0)return toast('Enter a goal name and target amount.');const idx=state.goals.findIndex(g=>g.id===id);if(idx>=0)state.goals[idx]=goal;else state.goals.unshift(goal);saveState();resetGoalForm();renderAll();toast(idx>=0?'Goal updated.':'Goal created.');}
function editGoal(id){const g=state.goals.find(x=>x.id===id);if(!g)return;navigate('goals');$('#goalId').value=g.id;$('#goalName').value=g.name;$('#goalTarget').value=g.target;$('#goalCurrent').value=g.current;$('#goalDate').value=g.targetDate||'';$('#goalFormTitle').textContent='Edit budget goal';$('#cancelGoalEdit').classList.remove('hidden');$('#goalName').focus();}
function resetGoalForm(){$('#goalForm').reset();$('#goalId').value='';$('#goalFormTitle').textContent='Create a budget goal';$('#cancelGoalEdit').classList.add('hidden');}
function deleteGoal(id){const g=state.goals.find(x=>x.id===id);if(!g||!confirm('Delete "'+g.name+'"? Related ledger entries will remain as historical records.'))return;state.goals=state.goals.filter(x=>x.id!==id);saveState();renderAll();toast('Goal deleted.');}
function quickGoalContribution(id){navigate('transactions');$('#transactionType').value='goal-contribution';renderTransactionTargets();$('#transactionTarget').value=id;$('#transactionDescription').value='Goal contribution';$('#transactionAmount').focus();}

function renderDebts(){
  $('#debtCountLabel').textContent=state.debts.length+(state.debts.length===1?' account':' accounts');const grid=$('#debtsGrid');if(!state.debts.length){grid.innerHTML=emptyState('Add your first debt','Track balances, APR, and daily or monthly payment schedules.');return;}
  const monthKey=isoDate(new Date()).slice(0,7);
  grid.innerHTML=state.debts.map(d=>{const original=Math.max(n(d.originalBalance),n(d.balance),1),p=clamp(((original-n(d.balance))/original)*100,0,100),paid=paymentsForDebt(d.id).filter(t=>t.date.startsWith(monthKey)).reduce((s,t)=>s+n(t.amount),0);return `<article class="finance-card"><div class="finance-card-header"><div><h3>${escapeHtml(d.name)}</h3><div class="subtitle">${escapeHtml(d.notes||(d.frequency==='daily'?'Daily payment schedule':'Monthly payment schedule'))}</div></div><div class="card-menu"><button data-action="edit-debt" data-id="${d.id}">Edit</button><button class="delete" data-action="delete-debt" data-id="${d.id}">Delete</button></div></div><div class="balance-line"><strong>${money(d.balance)}</strong><small>${percent(p)} reduced</small></div><div class="progress-track"><i style="width:${p}%"></i></div><div class="card-facts"><div class="fact"><span>APR</span><strong>${n(d.apr).toFixed(2)}%</strong></div><div class="fact"><span>Schedule</span><strong>${money(d.scheduledPayment,true)} ${d.frequency==='daily'?'/ day':'/ mo'}</strong></div><div class="fact"><span>Paid this mo</span><strong>${money(paid,true)}</strong></div></div><div class="card-actions"><button class="button primary" data-action="pay-debt" data-id="${d.id}">Log payment</button></div></article>`;}).join('');
}
function saveDebt(event){event.preventDefault();const id=$('#debtId').value,original=n($('#debtOriginal').value),balance=n($('#debtBalance').value);const d={id:id||uid('debt'),name:$('#debtName').value.trim(),originalBalance:Math.max(original||balance,balance),balance,apr:n($('#debtApr').value),scheduledPayment:n($('#debtPayment').value),frequency:$('#debtFrequency').value,dueDay:clamp(Number($('#debtDueDay').value)||1,1,31),notes:$('#debtNotes').value.trim(),createdAt:id?(state.debts.find(x=>x.id===id)?.createdAt||Date.now()):Date.now()};if(!d.name||d.originalBalance<=0)return toast('Enter a name and the amount you currently owe.');if(d.scheduledPayment<=0)return toast('Enter the amount you plan to pay '+(d.frequency==='daily'?'each day.':'each month.'));const idx=state.debts.findIndex(x=>x.id===id);if(idx>=0)state.debts[idx]=d;else state.debts.unshift(d);saveState();resetDebtForm();renderAll();toast(idx>=0?'Debt updated.':'Debt added.');}
function editDebt(id){const d=state.debts.find(x=>x.id===id);if(!d)return;navigate('debts');$('#debtId').value=d.id;$('#debtName').value=d.name;$('#debtOriginal').value=d.originalBalance;$('#debtBalance').value=d.balance;$('#debtApr').value=d.apr;$('#debtPayment').value=d.scheduledPayment;$('#debtFrequency').value=d.frequency;$('#debtDueDay').value=d.dueDay||1;$('#debtNotes').value=d.notes||'';$('#debtFormTitle').textContent='Edit debt';$('#cancelDebtEdit').classList.remove('hidden');toggleDueDay();$('#debtName').focus();}
function resetDebtForm(){$('#debtForm').reset();$('#debtId').value='';$('#debtApr').value='0';$('#debtFrequency').value='monthly';$('#debtDueDay').value='1';$('#debtFormTitle').textContent='Add a debt';$('#cancelDebtEdit').classList.add('hidden');toggleDueDay();}
function toggleDueDay(){const daily=$('#debtFrequency').value==='daily';$('#dueDayField').classList.toggle('hidden',daily);const label=$('#debtPaymentLabel'),help=$('#debtPaymentHelp');if(label)label.innerHTML=daily?'Amount you plan to pay each day <em>Required</em>':'Amount you plan to pay each month <em>Required</em>';if(help)help.textContent=daily?'Used for daily tracking and converted to a monthly average in the payoff planner.':'Used for monthly reminders and the payoff planner.';}
function deleteDebt(id){const d=state.debts.find(x=>x.id===id);if(!d||!confirm('Delete "'+d.name+'"? Historical transactions will remain.'))return;state.debts=state.debts.filter(x=>x.id!==id);saveState();renderAll();toast('Debt deleted.');}
function quickDebtPayment(id){navigate('transactions');$('#transactionType').value='debt-payment';renderTransactionTargets();$('#transactionTarget').value=id;$('#transactionDescription').value='Debt payment';$('#transactionAmount').focus();}
function paymentsForDebt(id){return state.transactions.filter(t=>t.type==='debt-payment'&&t.targetId===id);}
function scheduledMonthlyAmount(d){return d.frequency==='daily'?n(d.scheduledPayment)*30.4375:n(d.scheduledPayment);}

