function renderSettings(){$('#currencySelect').value=state.settings.currency||'VND';$('#reminderLeadDays').value=state.settings.reminderLeadDays??3;}
function saveSettings(event){event.preventDefault();state.settings.currency=$('#currencySelect').value;state.settings.reminderLeadDays=clamp(Number($('#reminderLeadDays').value)||0,0,30);saveState();renderAll();toast('Settings saved.');}
function renderReport(){const totalDebt=state.debts.reduce((s,d)=>s+n(d.balance),0),totalOriginal=state.debts.reduce((s,d)=>s+n(d.originalBalance),0),totalSaved=state.goals.reduce((s,g)=>s+n(g.current),0),totalGoal=state.goals.reduce((s,g)=>s+n(g.target),0),monthKey=isoDate(new Date()).slice(0,7),paidMonth=state.transactions.filter(t=>t.type==='debt-payment'&&t.date.startsWith(monthKey)).reduce((s,t)=>s+n(t.amount),0);$('#reportGenerated').textContent='Generated '+formatDate(new Date());$('#reportBody').innerHTML=`<div class="report-grid"><div class="report-stat"><span>Debt balance</span><strong>${money(totalDebt)}</strong></div><div class="report-stat"><span>Debt reduced</span><strong>${money(Math.max(0,totalOriginal-totalDebt))}</strong></div><div class="report-stat"><span>Goal savings</span><strong>${money(totalSaved)}</strong></div><div class="report-stat"><span>Paid this month</span><strong>${money(paidMonth)}</strong></div></div><div class="report-columns"><div class="report-block"><h3>Debt accounts</h3>${state.debts.length?state.debts.map(d=>`<div class="report-line"><span>${escapeHtml(d.name)}</span><strong>${money(d.balance)}</strong></div>`).join(''):'<div class="muted">No debts recorded.</div>'}</div><div class="report-block"><h3>Budget goals</h3>${state.goals.length?state.goals.map(g=>`<div class="report-line"><span>${escapeHtml(g.name)} (${percent(progressOfGoal(g))})</span><strong>${money(g.current)} / ${money(g.target)}</strong></div>`).join(''):'<div class="muted">No goals recorded.</div>'}</div></div><p class="fine-print">Goal target total: ${money(totalGoal)}. This report reflects locally stored data at the time it was generated.</p>`;}
function exportCsv(){const lines=[['date','type','description','account','amount','currency'].join(',')];sortedTransactions().forEach(t=>lines.push([t.date,transactionTypeLabel(t.type),t.description||'',transactionTargetName(t),n(t.amount),state.settings.currency].map(csvCell).join(',')));downloadFile('ledger-transactions-'+isoDate(new Date())+'.csv',lines.join('\n'),'text/csv;charset=utf-8');toast('CSV exported.');}
function csvCell(v){return '"'+String(v??'').replace(/"/g,'""')+'"';}
function exportJson(){downloadFile('ledger-hall-backup-'+isoDate(new Date())+'.json',JSON.stringify(state,null,2),'application/json');toast('Backup exported.');}
function downloadFile(filename,content,type){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function importJson(event){const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=JSON.parse(reader.result);if(!imported||!Array.isArray(imported.goals)||!Array.isArray(imported.debts)||!Array.isArray(imported.transactions))throw new Error();if(!confirm('Import this backup? It will replace the data currently stored in this browser.'))return;state={...structuredClone(defaultState),...imported,settings:{...defaultState.settings,...(imported.settings||{})}};saveState();applyTheme();renderAll();toast('Backup imported.');}catch{toast('Could not import that backup file.');}finally{event.target.value='';}};reader.readAsText(file);}
function resetAllData(){if(!confirm('Reset all Ledger Hall data in this browser? This cannot be undone unless you exported a backup.'))return;state=structuredClone(defaultState);saveState();applyTheme();resetGoalForm();resetDebtForm();$('#transactionForm').reset();$('#transactionDate').value=isoDate(new Date());renderAll();navigate('dashboard');toast('Local data reset.');}
