function renderTransactionTargets(){const type=$('#transactionType').value,field=$('#transactionTargetField'),select=$('#transactionTarget'),previous=select.value,needs=type==='debt-payment'||type==='goal-contribution';field.classList.toggle('hidden',!needs);if(!needs){select.innerHTML='';return;}const items=type==='debt-payment'?state.debts:state.goals,label=type==='debt-payment'?'Select debt':'Select goal';select.innerHTML=`<option value="">${label}</option>`+items.map(x=>`<option value="${x.id}">${escapeHtml(x.name)}</option>`).join('');if(items.some(x=>x.id===previous))select.value=previous;}
function saveTransaction(event){event.preventDefault();const type=$('#transactionType').value,needs=type==='debt-payment'||type==='goal-contribution',targetId=needs?$('#transactionTarget').value:'',amount=n($('#transactionAmount').value),date=$('#transactionDate').value;if(!amount||amount<=0||!date)return toast('Enter an amount and date.');if(needs&&!targetId)return toast('Select an account for this entry.');if(type==='debt-payment'){const d=state.debts.find(x=>x.id===targetId);if(!d)return toast('Debt account not found.');d.balance=Math.max(0,n(d.balance)-amount);}if(type==='goal-contribution'){const g=state.goals.find(x=>x.id===targetId);if(!g)return toast('Budget goal not found.');g.current=n(g.current)+amount;}state.transactions.unshift({id:uid('tx'),type,targetId,amount,date,description:$('#transactionDescription').value.trim(),createdAt:Date.now()});saveState();const keep=type;$('#transactionForm').reset();$('#transactionType').value=keep;$('#transactionDate').value=isoDate(new Date());renderAll();$('#transactionType').value=keep;renderTransactionTargets();toast('Transaction added.');}
function deleteTransaction(id){const t=state.transactions.find(x=>x.id===id);if(!t||!confirm('Delete this transaction? Linked balances will be adjusted.'))return;if(t.type==='debt-payment'){const d=state.debts.find(x=>x.id===t.targetId);if(d)d.balance=n(d.balance)+n(t.amount);}if(t.type==='goal-contribution'){const g=state.goals.find(x=>x.id===t.targetId);if(g)g.current=Math.max(0,n(g.current)-n(t.amount));}state.transactions=state.transactions.filter(x=>x.id!==id);saveState();renderAll();toast('Transaction deleted.');}
function sortedTransactions(){return [...state.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')||n(b.createdAt)-n(a.createdAt));}
function renderTransactions(){const filter=$('#transactionFilter').value,q=$('#transactionSearch').value.trim().toLowerCase();const items=sortedTransactions().filter(t=>(filter==='all'||t.type===filter)&&(!q||[t.description,transactionTargetName(t),transactionTypeLabel(t.type),t.date].join(' ').toLowerCase().includes(q)));$('#transactionsTable').innerHTML=items.length?items.map(t=>transactionRow(t,true)).join(''):tableEmpty(6,'No matching transactions.');}
function transactionRow(t,actions){const incoming=t.type==='income',sign=incoming?'+':'−',target=transactionTargetName(t)||(t.type==='income'?'Income':t.type==='expense'?'Expense':'Archived account');return `<tr><td>${formatDate(t.date,{month:'short',day:'numeric',year:'2-digit'})}</td><td><span class="type-pill">${escapeHtml(transactionTypeLabel(t.type))}</span></td><td><strong>${escapeHtml(t.description||transactionTypeLabel(t.type))}</strong></td><td>${escapeHtml(target)}</td><td class="numeric ${incoming?'amount-in':'amount-out'}">${sign}${money(t.amount)}</td>${actions?`<td class="numeric"><button class="row-delete" data-action="delete-transaction" data-id="${t.id}">Delete</button></td>`:''}</tr>`;}
function transactionTargetName(t){if(t.type==='debt-payment')return state.debts.find(d=>d.id===t.targetId)?.name||'';if(t.type==='goal-contribution')return state.goals.find(g=>g.id===t.targetId)?.name||'';return '';}
function transactionTypeLabel(type){return {'debt-payment':'Debt payment','goal-contribution':'Goal contribution','income':'Income','expense':'Expense'}[type]||type;}
function tableEmpty(cols,msg){return `<tr><td colspan="${cols}"><div class="empty-state">${escapeHtml(msg)}</div></td></tr>`;}
function emptyState(title,text){return `<div class="empty-state"><strong>${escapeHtml(title)}</strong>${escapeHtml(text)}</div>`;}

